name: llama_31_8B_instruct
framework: vllm #hf
model_name: meta-llama/Meta-Llama-3.1-8B-Instruct #Meta-Llama-3-8B-Instruct
model_path: meta-llama/Meta-Llama-3.1-8B-Instruct
max_input_length: 512
batch_size: 32
generation_params:
  do_sample: false
  temperature: 0.2
  top_p: 0.9
  max_tokens: 32