name: qwen2_0_5b_instruct
framework: vllm #vllm, hf, openai
model_name: Qwen/Qwen2-0.5B-Instruct
model_path: Qwen/Qwen2-0.5B-Instruct
max_input_length: 32768
batch_size: 32
openai_endpoint: http://134.197.95.82:8000

generation_params:
  do_sample: false
  temperature: 0.7
  top_k: 20
  top_p: 0.8
  max_tokens: 32768