name: rq_rag_llama2_7B
generator_framework: vllm
generator_model: chiminchan/rq_rag_llama2_7B #Meta-Llama-3-8B-Instruct
generator_max_input_length: 8096
generator_batch_size: 1

generation_params:
  do_sample: false
  temperature: 0.2
  top_p: 0.9
  max_tokens: 512
  skip_special_tokens: False