name: rq_rag_llama2_7B
framework: vllm
model_name: chiminchan/rq_rag_llama2_7B #Meta-Llama-3-8B-Instruct
model_path: chiminchan/rq_rag_llama2_7B
max_input_length: 4096
batch_size: 1

generation_params:
  do_sample: false
  temperature: 0.2
  top_p: 0.9
  max_tokens: 512
  skip_special_tokens: False