# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"O\n\nRAGRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x13\n\x0bquery_class\x18\x04 \x01(\t\"\xac\x01\n\x05Trace\x12\x13\n\x0bretrieve_ms\x18\x01 \x01(\x01\x12\x11\n\trerank_ms\x18\x02 \x01(\x01\x12\x14\n\x0cllm_queue_ms\x18\x03 \x01(\x01\x12\x11\n\tdecode_ms\x18\x04 \x01(\x01\x12\t\n\x01k\x18\x05 \x01(\x05\x12\x15\n\rprompt_tokens\x18\x06 \x01(\x05\x12\x15\n\routput_tokens\x18\x07 \x01(\x05\x12\x19\n\x11retrieved_doc_ids\x18\x08 \x03(\t\"8\n\x0bRAGResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x19\n\x05trace\x18\x02 \x01(\x0b\x32\n.rag.Trace28\n\nRAGService\x12*\n\x05Query\x12\x0f.rag.RAGRequest\x1a\x10.rag.RAGResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAGREQUEST']._serialized_start=18
  _globals['_RAGREQUEST']._serialized_end=97
  _globals['_TRACE']._serialized_start=100
  _globals['_TRACE']._serialized_end=272
  _globals['_RAGRESPONSE']._serialized_start=274
  _globals['_RAGRESPONSE']._serialized_end=330
  _globals['_RAGSERVICE']._serialized_start=332
  _globals['_RAGSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
