#facebook dpr embedder for natural questions
type: dpr
passage_encoder_id: sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base
query_encoder_id: sentence-transformers/facebook-dpr-question_encoder-single-nq-base
batch_size: 32
# normalize_embeddings: false
# metric: ip
# dim: 768


#multi-set models
# passage_encoder: sentence-transformers/facebook-dpr-ctx_encoder-multiset-base
# question_encoder: sentence-transformers/facebook-dpr-question_encoder-multiset-base