name: e5_flat_inner_21m

index_path: /home/pwatters/project/LogitRAG/data/indexes/wiki_dpr_100w/e5_flat_inner.index
corpus_path: /home/pwatters/project/LogitRAG/data/wiki_corpus/wiki18_100w.jsonl

retrieval_model: sentence-transformers/facebook-dpr-question_encoder-single-nq-base

top_k: 5

nprobe: null
ef_search: null

normalize_embeddings: True
faiss_gpu: false