name: wiki_dpr_hnsw_100k

index_path: s3://vectorindexes/wiki-dpr/faiss_wiki_dpr/hnsw_100k/index_psgs_w100_nq_no_index_hnsw_ip_100000.faiss
corpus_path: s3://vectorindexes/wiki-dpr/wiki-passages/100k/meta_psgs_w100_nq_no_index_100000_text.jsonl

retrieval_model: sentence-transformers/facebook-dpr-question_encoder-single-nq-base

top_k: 5

nprobe: null
ef_search: 64

normalize_embeddings: false
faiss_gpu: false