name: wiki_dpr_ivf_21m

index_path: s3://vectorindexes/wiki-dpr/faiss_wiki_dpr/ivf_2_5m/index_psgs_w100_nq_no_index_ivf_ip_21000000.faiss
corpus_path: s3://vectorindexes/wiki-dpr/wiki-passages/21m/meta_psgs_w100_nq_no_index_21000000_text.jsonl

retrieval_model: sentence-transformers/facebook-dpr-question_encoder-single-nq-base

top_k: 5

nprobe: 64
ef_search: null

normalize_embeddings: false
faiss_gpu: false