name: wiki_dpr_ivf_100k

index_path: s3://vectorindexes/wiki-dpr/faiss_wiki_dpr/ivf_100k/index_psgs_w100_nq_no_index_ivf_ip_100000.faiss
corpus_path: s3://vectorindexes/wiki-dpr/wiki-passages/100k/meta_psgs_w100_nq_no_index_100000_text.jsonl

retrieval_model: sentence-transformers/facebook-dpr-question_encoder-single-nq-base

tretrieval_topkk: 5

nprobe: 16
ef_search: null

normalize_embeddings: false
faiss_gpu: false