defaults:
  # - retriever: wiki_faiss_dpr_ivf_100k #, llama_13_8B_instruct, llama_70b_chat, gpt-3.5-turbo
  - generator:  llama_31_8B_instruct #qwen2_0_5b_instruct 
  - dataset: nq #nq, repeated_question
  - judger: null #skr, adaptive, null
  - retriever/pipeline: dense
  - retriever/corpus: wiki_21m #wiki_100k
  - retriever/encoder: dpr
  - retriever/index: wiki_dpr_ivf_21m #wiki_dpr_hnsw_100k
  - retriever/search: topk
  - retriever/cache: none # options: null, proximity
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_
  
retrieval_topk: 10
save_dir: results
run_name: null
# ------------
generator_device: cuda:0
retriever_encoder_device: cuda:0
judger_device: cu

metrics: ["em", "f1", "acc", "precision", "recall"]

max_sample_num: 500   # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples
is_reasoning: false

seed: 2024
batch_size: 1 #batch size for which items are processed
hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null


