defaults:
  # - retriever: wiki_faiss_dpr_ivf_100k #, llama_13_8B_instruct, llama_70b_chat, gpt-3.5-turbo
  - generator:  qwen2_0_5b_instruct #qwen2_0_5b_instruct 
  - dataset: repeated_question #nq, repeated_question, mmlu_econometrics
  - retriever/pipeline: all # options: sequential_rag,  llm_only, retrieval_only, flare, all
  - retriever/corpus: wiki_100k #wiki_100k
  - retriever/encoder: dpr
  - retriever/index: wiki_dpr_hnsw_100k #wiki_dpr_hnsw_100k
  - retriever/cache: none # options: null, proximity, none
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

retrieval_topk: 10
# ------------
generator_device: cuda:0
retriever_encoder_device: cuda:0
metrics: ["em", "f1", "acc", "precision", "recall"]
save_dir: results

max_sample_num: 5   # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples
is_reasoning: false

seed: 2024
batch_size: 1 #batch size for which items are sent through the pipeline

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null


