defaults:
  - generator:  meta_llama_31_8B_instruct #qwen2_0_5b_instruct, meta_llama_3_8B_Instruct, rq_rag_llama2_7B
    #nq, repeated_question, mmlu_econometrics, 2wiki, search_o1_test, hotpotqa
  - dataset: search_o1_test
    # options: sequential_rag,  llm_only, retrieval_only, flare, rqrag, all, search_o1, search_o1_vector
  - retriever/pipeline: search_o1 # search_o1_vector
  - retriever/corpus: wiki_100k #wiki_100k
  - retriever/encoder: dpr
  - retriever/index: wiki_dpr_hnsw_100k #wiki_dpr_hnsw_100k
  - retriever/cache: none # options: null, proximity, none
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

retrieval_topk: 2
# ------------
generator_device: cuda:0
retriever_encoder_device: cuda:0
metrics: ["em", "f1", "acc", "precision", "recall"]
save_dir: results

max_sample_num: null   # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples
is_reasoning: false

seed: 2024
batch_size: 1 #batch size for which items are sent through the pipeline

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null


