defaults:
  # - retriever: wiki_faiss_dpr_ivf_100k #, llama_13_8B_instruct, llama_70b_chat, gpt-3.5-turbo
  - generator:  qwen2_0_5b_instruct #qwen2_0_5b_instruct 
  - dataset: nq #nq, repeated_question
  - retriever/pipeline: dense
  - retriever/corpus: wiki_100k #wiki_100k
  - retriever/embedder: dpr
  - retriever/index: wiki_dpr_hnsw_100k #wiki_dpr_hnsw_100k
  - retriever/search: topk
  - retriever/cache: none # options: null, proximity, none
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

run_name: null
# ------------
generator_device: cuda:0
retriever_embedder_device: cuda:0

metrics: ["em", "f1", "acc", "precision", "recall"]
save_dir: results
save_sample_metrics: false
save_summary_metrics: false

max_sample_num: null   # number of samples to test (only work in dev/test split), if None, test all samples
random_sample: False # whether to randomly sample the test samples
is_reasoning: false

seed: 2024

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null


